# Generated by Django 5.1.6 on 2025-06-02 12:41

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_review_price_paid_dishrestaurantsuggestion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dishrestaurantsuggestion",
            options={
                "ordering": ["-created_date"],
                "verbose_name_plural": "Dish-Restaurant Suggestions",
            },
        ),
        migrations.AlterModelOptions(
            name="wishlist",
            options={"ordering": ["-created_date"]},
        ),
        migrations.RenameField(
            model_name="dishrestaurantsuggestion",
            old_name="submitted_at",
            new_name="created_date",
        ),
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="dishrestaurantsuggestion",
            name="available",
            field=models.BooleanField(default=True, help_text="Currently available?"),
        ),
        migrations.AlterField(
            model_name="dishrestaurantsuggestion",
            name="dish_name",
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name="dishrestaurantsuggestion",
            name="is_reviewed",
            field=models.BooleanField(
                default=False, help_text="Set to True when processed"
            ),
        ),
        migrations.AlterField(
            model_name="dishrestaurantsuggestion",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Suggested price in NOK",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0.1)],
            ),
        ),
        migrations.AlterField(
            model_name="dishrestaurantsuggestion",
            name="restaurant_name",
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="price_paid",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Suggested price in NOK",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0.1)],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AddConstraint(
            model_name="wishlist",
            constraint=models.UniqueConstraint(
                fields=("user", "dish"), name="unique_user_dish"
            ),
        ),
    ]
