# Generated by Django 5.1.6 on 2025-06-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_dishrestaurantsuggestion_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dishrestaurantsuggestion",
            name="local_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
