# Generated by Django 5.1.6 on 2025-06-02 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_dishrestaurantsuggestion_local_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                help_text="Rating must be between 0.1 and 5.0",
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
    ]
