# Generated by Django 5.1.6 on 2025-06-03 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.TextField(
                blank=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        1000, "Description cannot exceed 1000 characters."
                    ),
                    django.core.validators.MinLengthValidator(
                        5, "At least 5 characters."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dishrestaurantsuggestion",
            name="description",
            field=models.TextField(
                blank=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        1000, "Description cannot exceed 1000 characters."
                    ),
                    django.core.validators.MinLengthValidator(
                        5, "At least 5 characters."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="suggestions",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        20, "At least 20 characters"
                    ),
                    django.core.validators.MaxLengthValidator(
                        1000, "Can't exceed 1000"
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="description",
            field=models.TextField(
                blank=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        1000, "Description cannot exceed 1000 characters."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="description",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, "Review must be at least 5 characters."
                    ),
                    django.core.validators.MaxLengthValidator(
                        1000, "Review cannot exceed 1000 characters."
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="comments",
            field=models.TextField(
                blank=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        5, "Comments must be at least 5 characters."
                    ),
                    django.core.validators.MaxLengthValidator(
                        1000, "Comments cannot exceed 1000 characters."
                    ),
                ],
            ),
        ),
    ]
