# Generated by Django 5.1.6 on 2025-06-04 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_dish_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("user", "dish_restaurant"),
                name="unique_review_per_user_and_dishrest",
            ),
        ),
    ]
