# Generated by Django 5.1.6 on 2025-06-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_review_unique_review_per_user_and_dishrest"),
    ]

    operations = [
        migrations.AddField(
            model_name="dishrestaurant",
            name="categories",
            field=models.ManyToManyField(blank=True, to="myapp.category"),
        ),
    ]
